Algoritmo "05 sequencia impares"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Tcharles Souza
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Tcharles Souza
// Data atual  : 27/10/2022
Var

   i, x : inteiro

Inicio

   escreva("Digite o valor de X: ")
   leia(x)

   para i de 1 ate x faca
      se i % 2 <> 0 entao
         escreval(i)
      fimse
   fimpara

Fimalgoritmo