Algoritmo "05 tabuada"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Nelio Alves
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Tcharles Souza
// Data atual  : 26/10/2022
Var

x, i, produto : inteiro

Inicio
      escreva("Deseja a tabuada para qual número? ")
      leia(x)
      
      para i de 1 ate 10 faca
       produto <- x * i
       escreval (x, " X ", i, " = ", produto)
      fimpara


Fimalgoritmo